# PyInstaller hook - ensure rest_framework submodules are bundled
# DRF uses lazy imports; PyInstaller misses them without explicit hiddenimports
hiddenimports = [
    'rest_framework.negotiation',
    'rest_framework.renderers',
    'rest_framework.parsers',
    'rest_framework.authentication',
    'rest_framework.permissions',
    'rest_framework.throttling',
    'rest_framework.versioning',
    'rest_framework.metadata',
    'rest_framework.filters',
    'rest_framework.views',
    'rest_framework.viewsets',
    'rest_framework.generics',
    'rest_framework.decorators',
    'rest_framework.status',
    'rest_framework.serializers',
    'rest_framework.fields',
    'rest_framework.relations',
    'rest_framework.urls',
    'rest_framework.routers',
    'rest_framework.response',
    'rest_framework.request',
    'rest_framework.exceptions',
    'rest_framework.mixins',
    'rest_framework.pagination',
    'rest_framework.settings',
    'rest_framework.compat',
]
