#!/usr/bin/env bash
# Deploy a new isolated POS instance (one shop = one database, 256MB limit per container).
# Usage: ./setup_client.sh SHOP_NAME PORT
# Example: ./setup_client.sh myshop 8001
# Creates ./clients/SHOP_NAME/ with .env and docker-compose.yml, then runs docker-compose up -d.
# Run from repo root: ./deploy/multi-instance/setup_client.sh myshop 8001

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENTS_DIR="$SCRIPT_DIR/clients"

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: $0 SHOP_NAME PORT"
  echo "Example: $0 myshop 8001"
  exit 1
fi

# Normalize client name: lowercase, alphanumeric + underscore only (for container names and DB names)
CLIENT_NAME="$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]//g')"
PORT="$2"

if [ -z "$CLIENT_NAME" ]; then
  echo "Error: CLIENT_NAME must contain at least one letter or number."
  exit 1
fi

if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1024 ] || [ "$PORT" -gt 65535 ]; then
  echo "Error: PORT must be a number between 1024 and 65535."
  exit 1
fi

CLIENT_DIR="$CLIENTS_DIR/$CLIENT_NAME"
mkdir -p "$CLIENT_DIR"

if [ -f "$CLIENT_DIR/docker-compose.yml" ]; then
  echo "Warning: $CLIENT_DIR already exists. Overwriting docker-compose.yml and .env."
fi

# Generate secrets (alphanumeric + safe chars for DB password and Django SECRET_KEY)
generate_secret() {
  head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | head -c 48
}
DB_PASSWORD="$(generate_secret)"
SECRET_KEY="$(generate_secret)"
REDIS_PASSWORD="$(generate_secret)"

# Optional: set your contact for "Trial Expired" message (Myanmar + English)
TRIAL_CONTACT="${TRIAL_EXPIRED_CONTACT:-Contact: admin@example.com | +95 9 123 456 789}"

# Write .env for this client
cat > "$CLIENT_DIR/.env" << ENVFILE
# Generated by setup_client.sh - do not commit
CLIENT_NAME=$CLIENT_NAME
PORT=$PORT
DB_PASSWORD=$DB_PASSWORD
SECRET_KEY=$SECRET_KEY
REDIS_PASSWORD=$REDIS_PASSWORD
TRIAL_EXPIRED_CONTACT=$TRIAL_CONTACT
ENVFILE

# Copy template and substitute variables (container names and ports use env from .env when compose runs)
cp "$SCRIPT_DIR/docker-compose.template.yml" "$CLIENT_DIR/docker-compose.yml"

echo "Created $CLIENT_DIR with .env and docker-compose.yml"
echo "  Container names: pos_app_${CLIENT_NAME}, pos_db_${CLIENT_NAME}, pos_redis_${CLIENT_NAME}"
echo "  Database: pos_db_${CLIENT_NAME}"
echo "  Port: ${PORT}:8000"
echo ""
echo "Starting containers (project name: ${CLIENT_NAME})..."

cd "$CLIENT_DIR"
docker compose -p "$CLIENT_NAME" up -d --build

echo ""
echo "Done. POS instance for '$CLIENT_NAME' is starting."
echo "  URL: http://localhost:${PORT}/app/"
echo "  Admin: http://localhost:${PORT}/admin/"
echo "  First-time: Register at http://localhost:${PORT}/app/register"
echo "  Trial: 30 days from first run (trial_start_date set on first ShopSettings create)."
